### ISSUE TITLE
parse error

### ISSUE THREAD

**Issue by caasi** [g0v/slack-irc-plugin#8]
以下的錯誤會讓 slack-irc-plugin 停止運作：

```
SyntaxError: Unexpected token u
    at Object.parse (native)
    at Request._callback (/root/slack-irc-plugin/startups.js:37:20)
    at self.callback (/root/slack-irc-plugin/node_modules/request/request.js:122:22)
    at Request.emit (events.js:95:17)
    at ClientRequest.self.clientErrorHandler (/root/slack-irc-plugin/node_modules/request/request.js:231:10)
    at ClientRequest.emit (events.js:95:17)
    at CleartextStream.socketErrorListener (http.js:1548:9)
    at CleartextStream.emit (events.js:95:17)
    at SecurePair.<anonymous> (tls.js:1411:15)
    at SecurePair.emit (events.js:95:17)
```

**Comment by caasi** [comment]
member list 和 channel list API 可能會得到 `undefined` ，不知道發生的時機，先 catch 起來然後繼續。
